apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-fun-homelab-accessible-check
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: homelab-accessible-check
    name: cluster-fun (v2)
  source:
    path: manifests/homelab-accessible-check
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data

---
