apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-to-grist
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster.fun
  destination:
    namespace: cloudnative-now
    name: cluster-fun (v2)
  source:
    path: manifests/url-to-grist
    repoURL: "https://git.cluster.fun/AverageMarcus/cluster.fun.git"
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
---
